import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { boardPath, buildIndex, indexPath, regenerate, renderBoard } from '../.harness/bin/lib/board.mjs';
import { makeTask, tempHarness } from './helpers.mjs';

const SAMPLE = [
  makeTask({ id: 'EPIC-0001', type: 'epic', status: 'ready', title: 'Una épica contenedora de la fase' }),
  makeTask({ id: 'FEAT-0001', status: 'ready', priority: 'critical', size: 'M', parent: 'EPIC-0001' }),
  makeTask({ id: 'FEAT-0002', status: 'ready', depends_on: ['FEAT-0001'] }),
  makeTask({ id: 'FIX-0001', type: 'fix', status: 'done' }),
];

test('the index is byte-stable: regenerating twice changes nothing', () => {
  const { ctx, cleanup } = tempHarness({ tasks: SAMPLE });
  try {
    const first = regenerate(ctx);
    assert.ok(first.changed.length > 0, 'the first run must write');
    const indexBytes = fs.readFileSync(indexPath(ctx), 'utf8');
    const boardBytes = fs.readFileSync(boardPath(ctx), 'utf8');

    const second = regenerate(ctx);
    assert.deepEqual(second.changed, [], 'the second run must be a no-op');
    assert.equal(fs.readFileSync(indexPath(ctx), 'utf8'), indexBytes);
    assert.equal(fs.readFileSync(boardPath(ctx), 'utf8'), boardBytes);
  } finally {
    cleanup();
  }
});

test('no generated view contains a timestamp, or drift detection would be useless', () => {
  const { ctx, cleanup } = tempHarness({ tasks: SAMPLE });
  try {
    regenerate(ctx);
    const board = fs.readFileSync(boardPath(ctx), 'utf8');
    // The task's own updated_at is legitimate data; what must not appear is a generation time.
    assert.ok(!/generado el|generated at|\d{2}:\d{2}:\d{2}/.test(board), 'the board must not record when it was generated');
  } finally {
    cleanup();
  }
});

test('the index computes blocked from dependencies, and names the next task', () => {
  const index = buildIndex(SAMPLE);
  const byId = Object.fromEntries(index.tasks.map((t) => [t.id, t]));
  assert.equal(byId['FEAT-0002'].blocked, true, 'depends on an unfinished task');
  assert.equal(byId['FEAT-0001'].blocked, false);
  assert.equal(index.next, 'FEAT-0001', 'critical, unblocked, unclaimed, not an epic');
  assert.equal(index.counts.total, 4);
  assert.equal(index.counts.done, 1);
  assert.equal(index.counts.open, 3);
});

test('the index does not carry updated_at, so an unrelated edit does not make it stale', () => {
  // Recording a criterion's verdict bumps updated_at and changes nothing the index shows.
  // Including it made every such edit leave the index stale and doctor red for no reason.
  const [entry] = buildIndex(SAMPLE).tasks;
  assert.equal(entry.updated_at, undefined);
});

test('the index is sorted by id so diffs stay reviewable', () => {
  const shuffled = [SAMPLE[2], SAMPLE[0], SAMPLE[3], SAMPLE[1]];
  const ids = buildIndex(shuffled).tasks.map((t) => t.id);
  assert.deepEqual(ids, [...ids].sort());
});

test('the board is readable without knowing the harness', () => {
  const { ctx, cleanup } = tempHarness({ tasks: SAMPLE });
  try {
    const board = renderBoard(ctx, buildIndex(SAMPLE));
    assert.match(board, /GENERATED by harness/, 'must warn that it is generated');
    assert.match(board, /Listas para empezar/, 'columns are labelled in the project language');
    assert.match(board, /Hechas/);
    assert.match(board, /espera FEAT-0001/, 'a blocked task says what it waits for');
    assert.match(board, /harness index/, 'says how to regenerate rather than inviting hand edits');
  } finally {
    cleanup();
  }
});

test('a pipe in a title cannot break the markdown table', () => {
  const { ctx, cleanup } = tempHarness();
  try {
    const nasty = makeTask({ id: 'FEAT-0007', status: 'ready', title: 'Soportar a | b en el filtro de busqueda' });
    const board = renderBoard(ctx, buildIndex([nasty]));
    const row = board.split('\n').find((l) => l.includes('FEAT-0007'));
    assert.match(row, /a \\\| b/, 'the pipe must be escaped');
    // Only unescaped pipes delimit cells, which is what the markdown renderer sees.
    assert.equal(row.split(/(?<!\\)\|/).length, 8, 'the escaped pipe must not create an extra cell');
  } finally {
    cleanup();
  }
});
