import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import * as generate from '../.harness/bin/lib/generate.mjs';
import { AGENT_FIXTURE, COMMAND_FIXTURE, repoCtx, tempHarness } from './helpers.mjs';

function fixture() {
  return tempHarness({
    agents: [{ id: 'worker', content: AGENT_FIXTURE }],
    commands: [{ id: 'do-thing', content: COMMAND_FIXTURE }],
    project: { providers: { claude: true, agents_md: true } },
  });
}

test('neutral capabilities and model tiers are translated to the provider vocabulary', () => {
  const { ctx, cleanup } = fixture();
  try {
    const files = generate.plan(ctx);
    const agent = files.find((f) => f.path.endsWith(path.join('agents', 'worker.md')));
    assert.ok(agent, 'the agent must be projected');
    assert.match(agent.content, /^---\nname: worker\n/m);
    // read -> Read; edit -> Edit, Write
    assert.match(agent.content, /tools: Read, Edit, Write/);
    // primary -> sonnet
    assert.match(agent.content, /model: sonnet/);
    // The canonical vocabulary must not leak into the adapter.
    assert.ok(!/capabilities:/.test(agent.content), 'canonical keys must not appear in the adapter');
  } finally {
    cleanup();
  }
});

test('writes and forbidden become hard rules in the generated prompt', () => {
  const { ctx, cleanup } = fixture();
  try {
    const agent = generate.plan(ctx).find((f) => f.path.endsWith('worker.md'));
    assert.match(agent.content, /You may write to: src\. Nothing else\./);
    assert.match(agent.content, /You must never touch: tests\./);
  } finally {
    cleanup();
  }
});

test('a command projects its argument hint and allowed tools', () => {
  const { ctx, cleanup } = fixture();
  try {
    const cmd = generate.plan(ctx).find((f) => f.path.endsWith(path.join('commands', 'do-thing.md')));
    assert.match(cmd.content, /argument-hint: <TARGET>/);
    assert.match(cmd.content, /allowed-tools: Read, Bash/);
    assert.match(cmd.content, /Do the thing to \$1\./, 'the body and its placeholders survive');
  } finally {
    cleanup();
  }
});

test('every generated file carries the generated header', () => {
  const { ctx, cleanup } = fixture();
  try {
    for (const file of generate.plan(ctx)) {
      assert.match(file.content, /GENERATED by harness/, `${file.path} has no generated header`);
    }
  } finally {
    cleanup();
  }
});

test('output is deterministic, so drift detection means something', () => {
  const { ctx, cleanup } = fixture();
  try {
    const a = generate.plan(ctx).map((f) => `${f.path}\n${f.content}`).join('\n');
    const b = generate.plan(ctx).map((f) => `${f.path}\n${f.content}`).join('\n');
    assert.equal(a, b);
    assert.ok(!/\d{4}-\d{2}-\d{2}T/.test(a), 'no timestamps may appear in generated output');
  } finally {
    cleanup();
  }
});

test('check reports missing files, then drift, then nothing once applied', () => {
  const { ctx, cleanup } = fixture();
  try {
    assert.ok(generate.check(ctx).missing.length > 0, 'nothing generated yet');

    generate.apply(ctx);
    assert.deepEqual(generate.check(ctx), { drifted: [], missing: [] });

    const target = path.join(ctx.root, '.claude', 'agents', 'worker.md');
    fs.appendFileSync(target, '\nhand-edited\n');
    const after = generate.check(ctx);
    assert.equal(after.drifted.length, 1);
    assert.match(after.drifted[0], /worker\.md$/);

    // Regenerating restores it: the canonical source always wins.
    generate.apply(ctx);
    assert.deepEqual(generate.check(ctx), { drifted: [], missing: [] });
  } finally {
    cleanup();
  }
});

test('a harness:keep region survives regeneration', () => {
  const { ctx, cleanup } = fixture();
  try {
    generate.apply(ctx);
    const claudeMd = path.join(ctx.root, 'CLAUDE.md');
    const withKeep = `${fs.readFileSync(claudeMd, 'utf8')}\n<!-- harness:keep -->\nUna nota local que debe sobrevivir.\n<!-- /harness:keep -->\n`;
    fs.writeFileSync(claudeMd, withKeep);

    generate.apply(ctx);
    const regenerated = fs.readFileSync(claudeMd, 'utf8');
    assert.match(regenerated, /Una nota local que debe sobrevivir\./);
    assert.equal((regenerated.match(/harness:keep/g) || []).length, 2, 'exactly one keep block');
  } finally {
    cleanup();
  }
});

test('a provider turned off produces none of its files', () => {
  const { ctx, cleanup } = tempHarness({
    agents: [{ id: 'worker', content: AGENT_FIXTURE }],
    commands: [{ id: 'do-thing', content: COMMAND_FIXTURE }],
    project: { providers: { claude: false, agents_md: true } },
  });
  try {
    const paths = generate.plan(ctx).map((f) => f.path);
    assert.ok(!paths.some((p) => p.includes('.claude')), 'claude is off');
    assert.ok(!paths.includes('CLAUDE.md'));
    assert.ok(paths.includes('AGENTS.md'));
    assert.ok(paths.some((p) => p.includes('runbooks')), 'commands degrade to runbooks');
  } finally {
    cleanup();
  }
});

test('the real repository has no adapter drift', () => {
  const { drifted, missing } = generate.check(repoCtx());
  assert.deepEqual({ drifted, missing }, { drifted: [], missing: [] }, 'run `harness generate`');
});
